//! Emit `.nix` files that reconstruct the translated derivation graph using
//! `builtins.derivation` calls.
//!
//! [`emit`] produces a single self-contained file using `let` bindings.
//!
//! [`emit_dir`] produces one file per derivation under `store/`. Each file is a
//! standalone `builtins.derivation { … }` that references its peers directly via
//! `(import ../store/<file>.nix).<output>`, so Nix tracks them as
//! `inputDrvs`/`inputSrcs` and computes the same hashes as `nix derivation add`.
//! Source inputs (`-builder`/`-source`/`-patch`) are `builtins.path` references.

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::LazyLock;

use regex::Regex;

use crate::ast::{Derivation, derivation_name, store_path_name};
use crate::hash;

/// Regex matching a Nix store path (hash + name, no trailing slash/suffix).
static STORE_PATH_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"/nix/store/[a-z0-9]{32}-[a-zA-Z0-9._?=+-]+").unwrap());

/// Data collected during splicer translation for one derivation.
pub struct TranslatedDrv {
    pub guix_drv_path: String,
    #[allow(dead_code)]
    pub nix_drv_path: String,
    /// The derivation after path-rewriting, with output paths blanked.
    pub drv: Derivation,
    /// Output name → computed Nix output path (from `nix derivation show`).
    pub nix_outputs: HashMap<String, String>,
}

/// Generate a single `.nix` file containing all translated derivations.
pub fn emit(out_path: &Path, translated: &[TranslatedDrv]) -> Result<(), String> {
    let var_names = assign_var_names(translated);

    // Reverse map: nix output path → (variable name, output name).
    let mut output_to_var: HashMap<&str, (&str, &str)> = HashMap::new();
    for (i, td) in translated.iter().enumerate() {
        for (out_name, out_path) in &td.nix_outputs {
            output_to_var.insert(out_path.as_str(), (&var_names[i], out_name.as_str()));
        }
    }

    // Collect input sources that are NOT derivation outputs.
    let mut sources: HashMap<&str, String> = HashMap::new();
    let mut src_seen: HashMap<String, usize> = HashMap::new();
    for td in translated {
        for src in &td.drv.input_srcs {
            if output_to_var.contains_key(src.as_str()) || sources.contains_key(src.as_str()) {
                continue;
            }
            let base = format!("src_{}", sanitize_ident(store_path_name(src)));
            let count = src_seen.entry(base.clone()).or_insert(0);
            let name = if *count == 0 {
                base.clone()
            } else {
                format!("{base}_{count}")
            };
            *count += 1;
            sources.insert(src.as_str(), name);
        }
    }

    let mut nix = String::with_capacity(64 * 1024);
    nix.push_str("# Generated by guix-transfer\n");
    nix.push_str(
        "# Do not edit — regenerate with: guix-transfer --emit-nix <output.nix> <drv>\n\n",
    );
    nix.push_str("let\n");

    // Source bindings (builtins.storePath for non-drv store objects).
    for (path, var) in &sources {
        nix.push_str(&format!("  {var} = builtins.storePath {path};\n"));
    }
    if !sources.is_empty() {
        nix.push('\n');
    }

    // Derivation bindings.
    for (i, td) in translated.iter().enumerate() {
        let var = &var_names[i];
        let drv_name = derivation_name(&td.guix_drv_path);

        nix.push_str(&format!("  # {drv_name}\n"));
        nix.push_str(&format!("  {var} = builtins.derivation {{\n"));
        nix.push_str(&format!("    name = {q};\n", q = nix_str_literal(drv_name)));
        nix.push_str(&format!(
            "    system = {q};\n",
            q = nix_str_literal(&td.drv.system)
        ));
        nix.push_str(&format!(
            "    builder = {b};\n",
            b = interpolate(&td.drv.builder, &output_to_var, &sources)
        ));

        if !td.drv.args.is_empty() {
            nix.push_str("    args = [\n");
            for arg in &td.drv.args {
                nix.push_str(&format!(
                    "      {a}\n",
                    a = interpolate(arg, &output_to_var, &sources)
                ));
            }
            nix.push_str("    ];\n");
        }

        if !td.drv.input_srcs.is_empty() {
            nix.push_str("    srcs = [\n");
            for src in &td.drv.input_srcs {
                if let Some(var) = sources.get(src.as_str()) {
                    nix.push_str(&format!("      {var}\n"));
                }
            }
            nix.push_str("    ];\n");
        }

        // Multi-output declaration.
        let output_names: Vec<&str> = td.drv.outputs.iter().map(|o| o.name.as_str()).collect();
        if output_names.len() > 1 || output_names.first().copied() != Some("out") {
            let quoted: Vec<String> = output_names.iter().map(|n| format!("\"{n}\"")).collect();
            nix.push_str(&format!("    outputs = [{}];\n", quoted.join(" ")));
        }

        // Fixed-output derivation attributes.
        for out in &td.drv.outputs {
            if !out.hash.is_empty() {
                let executable = td.drv.env_get("executable") == Some("1");
                if let Ok(h) = hash::guix_to_nix(&out.hash_algo, &out.hash, executable) {
                    nix.push_str(&format!(
                        "    outputHash = {q};\n",
                        q = nix_str_literal(&h.sri)
                    ));
                    nix.push_str("    outputHashAlgo = \"sha256\";\n");
                    let mode = if h.method == "nar" {
                        "recursive"
                    } else {
                        &h.method
                    };
                    nix.push_str(&format!("    outputHashMode = \"{mode}\";\n"));
                }
            }
        }

        // Env vars.  The splicer injects `name`, `system`, `builder` into
        // env (matching what `builtins.derivation` does), so we skip them
        // here since they're already emitted as standard attributes above.
        // Output names and `outputHash*` are also handled separately.
        let skip: &[&str] = &[
            "name",
            "system",
            "builder",
            "outputs",
            "outputHash",
            "outputHashAlgo",
            "outputHashMode",
        ];
        for e in &td.drv.env {
            if skip.contains(&e.key.as_str()) {
                continue;
            }
            if output_names.contains(&e.key.as_str()) {
                continue;
            }
            nix.push_str(&format!(
                "    {k} = {v};\n",
                k = nix_attr_key(&e.key),
                v = interpolate(&e.value, &output_to_var, &sources)
            ));
        }

        nix.push_str("  };\n\n");
    }

    nix.push_str(&format!(
        "in\n  {}\n",
        var_names.last().ok_or("no derivations to emit")?
    ));

    fs::write(out_path, &nix).map_err(|e| format!("write {}: {e}", out_path.display()))?;
    Ok(())
}

// ── helpers ──────────────────────────────────────────────────────────────────

/// Assign a unique Nix variable name to each derivation.
fn assign_var_names(translated: &[TranslatedDrv]) -> Vec<String> {
    let mut names = Vec::with_capacity(translated.len());
    let mut seen: HashMap<String, usize> = HashMap::new();
    for td in translated {
        let base = sanitize_ident(derivation_name(&td.guix_drv_path));
        let count = seen.entry(base.clone()).or_insert(0);
        let name = if *count == 0 {
            base.clone()
        } else {
            format!("{base}_{count}")
        };
        *count += 1;
        names.push(name);
    }
    names
}

/// Turn an arbitrary string into a valid Nix identifier.
fn sanitize_ident(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if s.is_empty() {
        s = "_unnamed".to_string();
    }
    s
}

/// Escape a string for use inside Nix `"..."` (no surrounding quotes).
fn escape_nix(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'\\' => {
                out.push_str("\\\\");
                i += 1;
            }
            b'"' => {
                out.push_str("\\\"");
                i += 1;
            }
            b'$' if i + 1 < bytes.len() && bytes[i + 1] == b'{' => {
                out.push_str("\\${");
                i += 2;
            }
            b'\n' => {
                out.push_str("\\n");
                i += 1;
            }
            b'\r' => {
                out.push_str("\\r");
                i += 1;
            }
            b'\t' => {
                out.push_str("\\t");
                i += 1;
            }
            _ => {
                out.push(bytes[i] as char);
                i += 1;
            }
        }
    }
    out
}

/// A plain Nix string literal with no interpolation.
fn nix_str_literal(s: &str) -> String {
    format!("\"{}\"", escape_nix(s))
}

/// Produce a Nix string with `${var}` interpolation for known store paths.
fn interpolate(
    s: &str,
    output_to_var: &HashMap<&str, (&str, &str)>,
    sources: &HashMap<&str, String>,
) -> String {
    if !s.contains("/nix/store/") {
        return nix_str_literal(s);
    }

    let mut replacements: Vec<(usize, usize, String)> = Vec::new();
    for m in STORE_PATH_RE.find_iter(s) {
        let path = m.as_str();
        if let Some(&(var, out_name)) = output_to_var.get(path) {
            let interp = format!("${{{var}.{out_name}}}");
            replacements.push((m.start(), m.end(), interp));
        } else if let Some(var) = sources.get(path) {
            replacements.push((m.start(), m.end(), format!("${{{var}}}")));
        }
    }

    if replacements.is_empty() {
        return nix_str_literal(s);
    }

    let mut out = String::from("\"");
    let mut pos = 0;
    for (start, end, interp) in &replacements {
        out.push_str(&escape_nix(&s[pos..*start]));
        out.push_str(interp);
        pos = *end;
    }
    out.push_str(&escape_nix(&s[pos..]));
    out.push('"');
    out
}

/// Format an attribute key: bare if it's a valid Nix identifier, quoted otherwise.
fn nix_attr_key(key: &str) -> String {
    let valid = !key.is_empty()
        && key
            .chars()
            .next()
            .map(|c| c.is_alphabetic() || c == '_')
            .unwrap_or(false)
        && key
            .chars()
            .all(|c| c.is_alphanumeric() || c == '_' || c == '-' || c == '\'');
    if valid {
        key.to_string()
    } else {
        format!("\"{}\"", escape_nix(key))
    }
}

/// Generate a directory containing all translated derivations as separate .nix files and sources.
pub fn emit_dir(
    out_dir: &Path,
    translated: &[TranslatedDrv],
    map: &std::collections::HashMap<String, String>,
) -> Result<(), String> {
    let store_dir = out_dir.join("store");
    let sources_dir = out_dir.join("sources");

    if store_dir.exists() {
        remove_dir_all_force(&store_dir).map_err(|e| format!("clean store dir: {e}"))?;
    }
    if sources_dir.exists() {
        remove_dir_all_force(&sources_dir).map_err(|e| format!("clean sources dir: {e}"))?;
    }

    fs::create_dir_all(&store_dir).map_err(|e| format!("create store dir: {e}"))?;
    fs::create_dir_all(&sources_dir).map_err(|e| format!("create sources dir: {e}"))?;

    // Map output/drv paths to (drv_filename, output_name)
    let mut output_to_file: HashMap<String, (String, String)> = HashMap::new();
    for td in translated {
        let drv_filename = Path::new(&td.nix_drv_path)
            .file_name()
            .unwrap()
            .to_str()
            .unwrap()
            .replace(".drv", ".nix");
        output_to_file.insert(
            td.nix_drv_path.clone(),
            (drv_filename.clone(), "drvPath".to_string()),
        );
        for (out_name, out_path) in &td.nix_outputs {
            output_to_file.insert(out_path.clone(), (drv_filename.clone(), out_name.clone()));
        }
    }

    // Copy unique sources to sources/
    let mut copied_sources = std::collections::HashSet::new();
    for td in translated {
        for src_path in &td.drv.input_srcs {
            if copied_sources.contains(src_path) {
                continue;
            }
            copied_sources.insert(src_path.clone());
            let src_name = Path::new(src_path).file_name().unwrap().to_str().unwrap();
            let dest = sources_dir.join(src_name);
            let nix_path = map
                .get(src_path)
                .cloned()
                .unwrap_or_else(|| src_path.to_string());
            if let Err(e) = copy_recursive(Path::new(src_path), &dest) {
                eprintln!("WARNING: failed to copy source {nix_path}: {e}");
            }
        }
    }

    // Write each translated derivation to its own file
    for td in translated {
        let drv_filename = Path::new(&td.nix_drv_path)
            .file_name()
            .unwrap()
            .to_str()
            .unwrap()
            .replace(".drv", ".nix");
        let drv_name = derivation_name(&td.guix_drv_path);

        let mut nix = String::with_capacity(4096);
        nix.push_str("# Generated by guix-transfer\n");
        nix.push_str("builtins.derivation {\n");
        nix.push_str(&format!("  name = {q};\n", q = nix_str_literal(drv_name)));
        nix.push_str(&format!(
            "  system = {q};\n",
            q = nix_str_literal(&td.drv.system)
        ));
        nix.push_str(&format!(
            "  builder = {b};\n",
            b = interpolate_multi(&td.drv.builder, &output_to_file)
        ));

        if !td.drv.args.is_empty() {
            nix.push_str("  args = [\n");
            for arg in &td.drv.args {
                nix.push_str(&format!(
                    "    {a}\n",
                    a = interpolate_multi(arg, &output_to_file)
                ));
            }
            nix.push_str("  ];\n");
        }

        if !td.drv.input_srcs.is_empty() {
            nix.push_str("  srcs = [\n");
            for src in &td.drv.input_srcs {
                let src_name = Path::new(src).file_name().unwrap().to_str().unwrap();
                let name = crate::ast::store_path_name(src);
                nix.push_str(&format!(
                    "    (builtins.path {{ name = \"{name}\"; path = ./../sources/{src_name}; }})\n"
                ));
            }
            nix.push_str("  ];\n");
        }

        let output_names: Vec<&str> = td.drv.outputs.iter().map(|o| o.name.as_str()).collect();
        if output_names.len() > 1 || output_names.first().copied() != Some("out") {
            let quoted: Vec<String> = output_names.iter().map(|n| format!("\"{n}\"")).collect();
            nix.push_str(&format!("  outputs = [{}];\n", quoted.join(" ")));
        }

        for out in &td.drv.outputs {
            if !out.hash.is_empty() {
                let executable = td.drv.env_get("executable") == Some("1");
                if let Ok(h) = hash::guix_to_nix(&out.hash_algo, &out.hash, executable) {
                    nix.push_str(&format!(
                        "  outputHash = {q};\n",
                        q = nix_str_literal(&h.sri)
                    ));
                    nix.push_str("  outputHashAlgo = \"sha256\";\n");
                    let mode = if h.method == "nar" {
                        "recursive"
                    } else {
                        &h.method
                    };
                    nix.push_str(&format!("  outputHashMode = \"{mode}\";\n"));
                }
            }
        }

        let skip: &[&str] = &[
            "name",
            "system",
            "builder",
            "outputs",
            "outputHash",
            "outputHashAlgo",
            "outputHashMode",
            "srcs",
        ];
        for e in &td.drv.env {
            if skip.contains(&e.key.as_str()) {
                continue;
            }
            if output_names.contains(&e.key.as_str()) {
                continue;
            }
            nix.push_str(&format!(
                "  {k} = {v};\n",
                k = nix_attr_key(&e.key),
                v = interpolate_multi(&e.value, &output_to_file)
            ));
        }

        nix.push_str("}\n");

        let file_path = store_dir.join(&drv_filename);
        fs::write(&file_path, &nix).map_err(|e| format!("write {}: {e}", file_path.display()))?;
    }

    Ok(())
}

/// After [`emit_dir`], verify that every emitted `.nix` evaluates to the *same*
/// derivation path that `nix derivation add` produced during translation.
///
/// guix-transfer computes each package's store path twice: once via
/// `nix derivation add` (whose output paths get baked into *consumer* builder
/// scripts through the rewrite map) and once via the emitted `builtins.derivation`
/// `.nix` file (what Nix actually builds). These MUST agree. If they diverge for
/// some derivations — e.g. a multi-output env-var mismatch between [`crate::json`]
/// and this module — every consumer bakes a store path that is never built, and
/// the tree is silently "split-brain" (classic symptom downstream:
/// `ld: cannot find crt1.o` / `-lc`). This check turns that silent corruption
/// into a hard, descriptive failure at sync time.
pub fn verify_consistency(out_dir: &Path, translated: &[TranslatedDrv]) -> Result<(), String> {
    use std::process::Command;

    let store_dir = out_dir.join("store");
    let store_abs = fs::canonicalize(&store_dir)
        .map_err(|e| format!("canonicalize {}: {e}", store_dir.display()))?;
    let store_abs = store_abs.to_str().ok_or("non-utf8 store path")?;

    // filename (`<hash>-<name>.nix`) -> expected `.drv` path from `nix derivation add`.
    let mut expected: HashMap<String, String> = HashMap::new();
    for td in translated {
        let fname = Path::new(&td.nix_drv_path)
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or("bad nix_drv_path")?
            .replace(".drv", ".nix");
        expected.insert(fname, td.nix_drv_path.clone());
    }

    // Evaluate every emitted .nix file's drvPath in a single pass.
    let expr = format!(
        "let d = {store_abs}; in builtins.mapAttrs (n: _: (import (d + (\"/\" + n))).drvPath) (builtins.readDir d)"
    );
    let output = Command::new("nix")
        .args(["eval", "--impure", "--json", "--expr", &expr])
        .output()
        .map_err(|e| format!("running `nix eval` for consistency check: {e}"))?;
    if !output.status.success() {
        return Err(format!(
            "consistency check could not evaluate the emitted store:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let actual: HashMap<String, String> = serde_json::from_slice(&output.stdout)
        .map_err(|e| format!("parsing consistency eval output: {e}"))?;

    let mut mismatches: Vec<(String, String, String)> = Vec::new();
    for (fname, exp) in &expected {
        match actual.get(fname) {
            Some(act) if act == exp => {}
            Some(act) => mismatches.push((fname.clone(), exp.clone(), act.clone())),
            None => mismatches.push((fname.clone(), exp.clone(), String::new())),
        }
    }
    mismatches.sort();

    if mismatches.is_empty() {
        return Ok(());
    }

    let mut report = String::new();
    for (fname, exp, act) in &mismatches {
        if act.is_empty() {
            report.push_str(&format!("  {fname}: emitted .nix missing from store dir\n"));
        } else {
            report.push_str(&format!(
                "  {fname}\n      nix derivation add (baked into consumers): {exp}\n      emitted .nix evaluates to                 : {act}\n"
            ));
        }
    }

    // For the first mismatch with both .drv paths available, dump the exact
    // structural diff (builder/args/env/inputDrvs/inputSrcs/outputs). Both .drv
    // files exist now (D1 from `nix derivation add`, D2 was just instantiated by
    // the eval above), so this pinpoints WHICH field diverges — the precise
    // signal needed to fix json.rs / emit_nix without guessing.
    if let Some((fname, d1, d2)) = mismatches.iter().find(|(_, _, a)| !a.is_empty())
        && let Some(diff) = diff_drvs(d1, d2)
    {
        report.push_str(&format!(
            "\n── structural diff of the first mismatch ({fname}) ──\n  D1 = nix derivation add (baked path): {d1}\n  D2 = emitted .nix (built path)      : {d2}\n{diff}"
        ));
    }

    Err(format!(
        "CONSISTENCY CHECK FAILED: {} derivation(s) whose `nix derivation add` path (baked into \
         consumer builder scripts via the rewrite map) does not match the path the emitted `.nix` \
         actually builds. Consumers would reference store paths that are never built (classic \
         downstream symptom: `ld: cannot find crt1.o` / `-lc`). This means json.rs and emit_nix \
         disagree for these derivations.\n{}",
        mismatches.len(),
        report
    ))
}

/// `nix derivation show` a `.drv` and return its single derivation object.
fn show_drv(path: &str) -> Option<serde_json::Value> {
    let out = std::process::Command::new("nix")
        .args(["derivation", "show", path])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).ok()?;
    // { "<path>": {...} } or { "derivations": { "<path>": {...} } }
    let map = v.get("derivations").unwrap_or(&v).as_object()?;
    map.values().next().cloned()
}

/// Produce a human-readable structural diff between two derivations (D1 vs D2),
/// reporting only the fields that differ. Returns None if either can't be shown.
fn diff_drvs(d1_path: &str, d2_path: &str) -> Option<String> {
    let a = show_drv(d1_path)?;
    let b = show_drv(d2_path)?;
    let mut out = String::new();

    // env: compare key sets and values (ignore output-name vars, which Nix
    // blanks during hashing, to avoid noise).
    let empty = serde_json::Map::new();
    let ea = a.get("env").and_then(|v| v.as_object()).unwrap_or(&empty);
    let eb = b.get("env").and_then(|v| v.as_object()).unwrap_or(&empty);
    let out_names: std::collections::HashSet<&str> = a
        .get("outputs")
        .and_then(|v| v.as_object())
        .map(|o| o.keys().map(|s| s.as_str()).collect())
        .unwrap_or_default();
    let mut env_lines = Vec::new();
    let mut keys: Vec<&String> = ea.keys().chain(eb.keys()).collect();
    keys.sort();
    keys.dedup();
    for k in keys {
        if out_names.contains(k.as_str()) {
            continue;
        }
        let va = ea.get(k).and_then(|v| v.as_str());
        let vb = eb.get(k).and_then(|v| v.as_str());
        if va != vb {
            env_lines.push(format!(
                "      env[{k}]:\n        D1: {}\n        D2: {}",
                va.unwrap_or("<absent>"),
                vb.unwrap_or("<absent>")
            ));
        }
    }
    if !env_lines.is_empty() {
        out.push_str("  env differs:\n");
        out.push_str(&env_lines.join("\n"));
        out.push('\n');
    }

    // inputDrvs, inputSrcs, args, builder
    for field in ["builder"] {
        if a.get(field) != b.get(field) {
            out.push_str(&format!(
                "  {field} differs:\n    D1: {}\n    D2: {}\n",
                a.get(field).map(|v| v.to_string()).unwrap_or_default(),
                b.get(field).map(|v| v.to_string()).unwrap_or_default()
            ));
        }
    }
    if a.get("args") != b.get("args") {
        out.push_str("  args differ\n");
    }

    // inputs.drvs: compare per-input output sets
    let ia = a
        .get("inputs")
        .and_then(|i| i.get("drvs"))
        .and_then(|v| v.as_object());
    let ib = b
        .get("inputs")
        .and_then(|i| i.get("drvs"))
        .and_then(|v| v.as_object());
    if let (Some(ia), Some(ib)) = (ia, ib) {
        let mut dk: Vec<&String> = ia.keys().chain(ib.keys()).collect();
        dk.sort();
        dk.dedup();
        let mut lines = Vec::new();
        for k in dk {
            let oa = ia.get(k).and_then(|v| v.get("outputs"));
            let ob = ib.get(k).and_then(|v| v.get("outputs"));
            if oa != ob {
                lines.push(format!(
                    "      {k}\n        D1 outputs: {}\n        D2 outputs: {}",
                    oa.map(|v| v.to_string()).unwrap_or("<absent>".into()),
                    ob.map(|v| v.to_string()).unwrap_or("<absent>".into())
                ));
            }
        }
        if !lines.is_empty() {
            out.push_str("  inputs.drvs differ (input → outputs used):\n");
            out.push_str(&lines.join("\n"));
            out.push('\n');
        }
    }

    // inputs.srcs
    let sa = a.get("inputs").and_then(|i| i.get("srcs"));
    let sb = b.get("inputs").and_then(|i| i.get("srcs"));
    if sa != sb {
        out.push_str(&format!(
            "  inputs.srcs differ:\n    D1: {}\n    D2: {}\n",
            sa.map(|v| v.to_string()).unwrap_or_default(),
            sb.map(|v| v.to_string()).unwrap_or_default()
        ));
    }

    if out.is_empty() {
        out.push_str("  (no field-level diff found — drvs differ only via input-path hashes)\n");
    }
    Some(out)
}

#[allow(clippy::permissions_set_readonly_false)]
fn copy_recursive(src: &Path, dst: &Path) -> Result<(), String> {
    let meta = fs::metadata(src).map_err(|e| format!("stat {}: {e}", src.display()))?;
    if meta.is_dir() {
        fs::create_dir_all(dst).map_err(|e| format!("mkdir {}: {e}", dst.display()))?;
        for entry in fs::read_dir(src).map_err(|e| format!("read dir {}: {e}", src.display()))? {
            let entry = entry.map_err(|e| format!("read entry: {e}"))?;
            let entry_path = entry.path();
            let dest_path = dst.join(entry.file_name());
            copy_recursive(&entry_path, &dest_path)?;
        }
    } else {
        if let Some(parent) = dst.parent() {
            fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        }
        fs::copy(src, dst)
            .map_err(|e| format!("copy {} -> {}: {e}", src.display(), dst.display()))?;
        let mut perms = fs::metadata(dst)
            .map_err(|e| format!("stat {}: {e}", dst.display()))?
            .permissions();
        if perms.readonly() {
            perms.set_readonly(false);
            fs::set_permissions(dst, perms)
                .map_err(|e| format!("set perms on {}: {e}", dst.display()))?;
        }
    }
    Ok(())
}

fn remove_dir_all_force(path: &Path) -> std::io::Result<()> {
    if !path.exists() {
        return Ok(());
    }
    set_writeable_recursive(path)?;
    fs::remove_dir_all(path)
}

#[allow(clippy::permissions_set_readonly_false)]
fn set_writeable_recursive(path: &Path) -> std::io::Result<()> {
    let meta = fs::metadata(path)?;
    let mut perms = meta.permissions();
    if perms.readonly() {
        perms.set_readonly(false);
        fs::set_permissions(path, perms)?;
    }
    if meta.is_dir() {
        for entry in fs::read_dir(path)? {
            let entry = entry?;
            set_writeable_recursive(&entry.path())?;
        }
    }
    Ok(())
}

fn interpolate_multi(s: &str, output_to_file: &HashMap<String, (String, String)>) -> String {
    if !s.contains("/nix/store/") {
        return nix_str_literal(s);
    }

    let mut replacements: Vec<(usize, usize, String)> = Vec::new();
    for m in STORE_PATH_RE.find_iter(s) {
        let path = m.as_str();
        if let Some((drv_filename, out_name)) = output_to_file.get(path) {
            let interp = if out_name == "drvPath" {
                format!("${{(import ../store/{drv_filename}).drvPath}}")
            } else {
                format!("${{(import ../store/{drv_filename}).{out_name}}}")
            };
            replacements.push((m.start(), m.end(), interp));
        } else if path.contains("-source")
            || path.contains("-builder")
            || path.contains("-patch")
            || !path.ends_with(".drv")
        {
            let filename = Path::new(path).file_name().unwrap().to_str().unwrap();
            let name = crate::ast::store_path_name(path);
            replacements.push((
                m.start(),
                m.end(),
                format!(
                    "${{builtins.path {{ name = ''{name}''; path = ./../sources/{filename}; }}}}"
                ),
            ));
        }
    }

    if replacements.is_empty() {
        return nix_str_literal(s);
    }

    let mut out = String::from("\"");
    let mut pos = 0;
    for (start, end, interp) in &replacements {
        out.push_str(&escape_nix(&s[pos..*start]));
        out.push_str(interp);
        pos = *end;
    }
    out.push_str(&escape_nix(&s[pos..]));
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{EnvVar, Output};

    /// Regression test for the "split-brain tree" bug.
    ///
    /// guix-transfer serializes each derivation two ways that MUST agree:
    ///   * `json::to_nix_json` → `nix derivation add` — the path baked into
    ///     consumer builder scripts via the rewrite map.
    ///   * `emit_nix::emit` → `builtins.derivation` — the `.nix` Nix actually
    ///     builds.
    ///
    /// These once diverged for *multi-output* derivations (an env-var mismatch),
    /// so consumers baked a glibc path that was never built — surfacing far
    /// downstream as `ld: cannot find crt1.o` / `-lc`. This test feeds one
    /// 3-output derivation through both paths and asserts the resulting `.drv`
    /// paths are identical. Requires `nix` on PATH.
    #[test]
    fn multi_output_json_and_nix_agree() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        // This test shells out to `nix derivation add`/`nix eval`. Inside the Nix
        // build sandbox (`nix build .#default`'s check phase) there is no `nix` on
        // PATH, so skip rather than fail there; it still runs in the dev shell/CI
        // where nix is available.
        if Command::new("nix").arg("--version").output().is_err() {
            eprintln!("skipping multi_output_json_and_nix_agree: `nix` not on PATH");
            return;
        }

        // Mirror what the splicer hands the serializers: name/system/builder
        // injected into env, output paths blanked, output-name env vars present
        // but empty.
        let guix_drv = "/gnu/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-multi-test.drv";
        let mk_out = |n: &str| Output {
            name: n.into(),
            path: String::new(),
            hash_algo: String::new(),
            hash: String::new(),
        };
        let drv = Derivation {
            outputs: vec![mk_out("debug"), mk_out("out"), mk_out("static")],
            input_drvs: vec![],
            input_srcs: vec![],
            system: "x86_64-linux".into(),
            builder: "/bin/sh".into(),
            args: vec!["-c".into(), "echo hi > $out".into()],
            env: vec![
                EnvVar {
                    key: "name".into(),
                    value: "multi-test".into(),
                },
                EnvVar {
                    key: "system".into(),
                    value: "x86_64-linux".into(),
                },
                EnvVar {
                    key: "builder".into(),
                    value: "/bin/sh".into(),
                },
                EnvVar {
                    key: "debug".into(),
                    value: String::new(),
                },
                EnvVar {
                    key: "out".into(),
                    value: String::new(),
                },
                EnvVar {
                    key: "static".into(),
                    value: String::new(),
                },
            ],
        };

        // Path A: json.rs → `nix derivation add` (what gets baked into consumers).
        let json = crate::json::to_nix_json(&drv, guix_drv).expect("to_nix_json");
        let mut add = Command::new("nix")
            .args(["derivation", "add"])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("spawn `nix derivation add` (is nix on PATH?)");
        add.stdin
            .take()
            .unwrap()
            .write_all(json.to_string().as_bytes())
            .unwrap();
        let add_out = add.wait_with_output().unwrap();
        assert!(
            add_out.status.success(),
            "nix derivation add failed: {}",
            String::from_utf8_lossy(&add_out.stderr)
        );
        let path_a = String::from_utf8(add_out.stdout)
            .unwrap()
            .trim()
            .to_string();

        // Path B: emit_nix → `builtins.derivation` (what Nix actually builds).
        let dir = std::env::temp_dir().join(format!("gt-consistency-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let nix_file = dir.join("multi-test.nix");
        let td = TranslatedDrv {
            guix_drv_path: guix_drv.to_string(),
            nix_drv_path: format!("/nix/store/{}.drv", "x".repeat(32) + "-multi-test"),
            drv: drv.clone(),
            nix_outputs: HashMap::new(),
        };
        emit(&nix_file, std::slice::from_ref(&td)).expect("emit");
        let eval = Command::new("nix")
            .args(["eval", "--impure", "--raw", "--expr"])
            .arg(format!("(import {}).drvPath", nix_file.display()))
            .output()
            .expect("spawn `nix eval`");
        assert!(
            eval.status.success(),
            "nix eval failed: {}",
            String::from_utf8_lossy(&eval.stderr)
        );
        let path_b = String::from_utf8(eval.stdout).unwrap().trim().to_string();
        let _ = fs::remove_dir_all(&dir);

        assert_eq!(
            path_a, path_b,
            "json.rs (nix derivation add) and emit_nix (builtins.derivation) produced \
             different .drv paths for a multi-output derivation — consumers would bake a \
             path that is never built (the split-brain bug)."
        );
    }

    #[test]
    fn sanitize_ident_basic() {
        assert_eq!(sanitize_ident("hello-2.12.2"), "hello_2_12_2");
        assert_eq!(sanitize_ident("0xdeadbeef"), "_0xdeadbeef");
        assert_eq!(
            sanitize_ident("gcc-core-mesboot0-2.95.3"),
            "gcc_core_mesboot0_2_95_3"
        );
    }

    #[test]
    fn escape_nix_basic() {
        assert_eq!(escape_nix("hello"), "hello");
        assert_eq!(escape_nix("a\"b"), "a\\\"b");
        assert_eq!(escape_nix("${foo}"), "\\${foo}");
        assert_eq!(escape_nix("$out"), "$out");
        assert_eq!(escape_nix("a\\b"), "a\\\\b");
    }

    #[test]
    fn interpolate_replaces_known_paths() {
        let mut outputs = HashMap::new();
        outputs.insert(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-gcc",
            ("gcc", "out"),
        );
        let sources = HashMap::new();
        assert_eq!(
            interpolate(
                "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-gcc/bin/gcc",
                &outputs,
                &sources
            ),
            "\"${gcc.out}/bin/gcc\""
        );
    }

    #[test]
    fn interpolate_preserves_unknown_paths() {
        let outputs = HashMap::new();
        let sources = HashMap::new();
        assert_eq!(
            interpolate(
                "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-unknown/bin/x",
                &outputs,
                &sources
            ),
            "\"/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-unknown/bin/x\""
        );
    }

    #[test]
    fn interpolate_handles_shell_dollar_brace() {
        let mut outputs = HashMap::new();
        outputs.insert(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-dep",
            ("dep", "out"),
        );
        let sources = HashMap::new();
        assert_eq!(
            interpolate(
                "echo ${foo} /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-dep/bin/x",
                &outputs,
                &sources
            ),
            "\"echo \\${foo} ${dep.out}/bin/x\""
        );
    }

    #[test]
    fn interpolate_multi_output() {
        let mut outputs = HashMap::new();
        outputs.insert(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-pkg-lib",
            ("pkg", "lib"),
        );
        let sources = HashMap::new();
        assert_eq!(
            interpolate(
                "-L/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-pkg-lib/lib",
                &outputs,
                &sources
            ),
            "\"-L${pkg.lib}/lib\""
        );
    }

    #[test]
    fn interpolate_multi_refs_import_output() {
        let mut m = HashMap::new();
        m.insert(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-gcc".to_string(),
            (
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-gcc.nix".to_string(),
                "out".to_string(),
            ),
        );
        assert_eq!(
            interpolate_multi(
                "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-gcc/bin/gcc",
                &m
            ),
            "\"${(import ../store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-gcc.nix).out}/bin/gcc\""
        );
    }

    #[test]
    fn interpolate_multi_refs_import_drvpath() {
        let mut m = HashMap::new();
        m.insert(
            "/nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-foo.drv".to_string(),
            (
                "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-foo.nix".to_string(),
                "drvPath".to_string(),
            ),
        );
        assert_eq!(
            interpolate_multi("/nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-foo.drv", &m),
            "\"${(import ../store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-foo.nix).drvPath}\""
        );
    }

    #[test]
    fn var_names_are_unique() {
        use crate::ast::Derivation;
        let mk = |name: &str| TranslatedDrv {
            guix_drv_path: format!("/gnu/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-{name}.drv"),
            nix_drv_path: String::new(),
            drv: Derivation {
                outputs: vec![],
                input_drvs: vec![],
                input_srcs: vec![],
                system: String::new(),
                builder: String::new(),
                args: vec![],
                env: vec![],
            },
            nix_outputs: HashMap::new(),
        };
        let tds = vec![
            mk("module-import-compiled"),
            mk("module-import-compiled"),
            mk("module-import-compiled"),
        ];
        let names = assign_var_names(&tds);
        assert_eq!(names[0], "module_import_compiled");
        assert_eq!(names[1], "module_import_compiled_1");
        assert_eq!(names[2], "module_import_compiled_2");
    }
}
