//! Emit a self-contained `.nix` file that reconstructs the translated derivation
//! graph using `builtins.derivation` calls.  Dependencies are expressed as Nix
//! `let` bindings with `import`-style references (via string interpolation), so
//! Nix tracks them as `inputDrvs`/`inputSrcs` and computes the same derivation
//! hashes as `nix derivation add`.

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::LazyLock;

use regex::Regex;

use crate::ast::{derivation_name, store_path_name, Derivation};
use crate::hash;

/// Regex matching a Nix store path (hash + name, no trailing slash/suffix).
static STORE_PATH_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"/nix/store/[a-z0-9]{32}-[a-zA-Z0-9._?=+-]+").unwrap());

/// Data collected during splicer translation for one derivation.
pub struct TranslatedDrv {
    pub guix_drv_path: String,
    pub nix_drv_path: String,
    /// The derivation after path-rewriting, with output paths blanked.
    pub drv: Derivation,
    /// Output name → computed Nix output path (from `nix derivation show`).
    pub nix_outputs: HashMap<String, String>,
}

/// Generate a single `.nix` file containing all translated derivations.
pub fn emit(out_path: &Path, translated: &[TranslatedDrv]) -> Result<(), String> {
    let var_names = assign_var_names(translated);

    // Reverse map: nix output path → (variable name, output name).
    let mut output_to_var: HashMap<&str, (&str, &str)> = HashMap::new();
    for (i, td) in translated.iter().enumerate() {
        for (out_name, out_path) in &td.nix_outputs {
            output_to_var.insert(out_path.as_str(), (&var_names[i], out_name.as_str()));
        }
    }

    // Collect input sources that are NOT derivation outputs.
    let mut sources: HashMap<&str, String> = HashMap::new();
    let mut src_seen: HashMap<String, usize> = HashMap::new();
    for td in translated {
        for src in &td.drv.input_srcs {
            if output_to_var.contains_key(src.as_str()) || sources.contains_key(src.as_str()) {
                continue;
            }
            let base = format!("src_{}", sanitize_ident(store_path_name(src)));
            let count = src_seen.entry(base.clone()).or_insert(0);
            let name = if *count == 0 {
                base.clone()
            } else {
                format!("{base}_{count}")
            };
            *count += 1;
            sources.insert(src.as_str(), name);
        }
    }

    let mut nix = String::with_capacity(64 * 1024);
    nix.push_str("# Generated by guix-transfer\n");
    nix.push_str("# Do not edit — regenerate with: guix-transfer --emit-nix <output.nix> <drv>\n\n");
    nix.push_str("let\n");

    // Source bindings (builtins.storePath for non-drv store objects).
    for (path, var) in &sources {
        nix.push_str(&format!("  {var} = builtins.storePath {path};\n"));
    }
    if !sources.is_empty() {
        nix.push('\n');
    }

    // Derivation bindings.
    for (i, td) in translated.iter().enumerate() {
        let var = &var_names[i];
        let drv_name = derivation_name(&td.guix_drv_path);

        nix.push_str(&format!("  # {drv_name}\n"));
        nix.push_str(&format!("  {var} = builtins.derivation {{\n"));
        nix.push_str(&format!(
            "    name = {q};\n",
            q = nix_str_literal(drv_name)
        ));
        nix.push_str(&format!(
            "    system = {q};\n",
            q = nix_str_literal(&td.drv.system)
        ));
        nix.push_str(&format!(
            "    builder = {b};\n",
            b = interpolate(&td.drv.builder, &output_to_var, &sources)
        ));

        if !td.drv.args.is_empty() {
            nix.push_str("    args = [\n");
            for arg in &td.drv.args {
                nix.push_str(&format!(
                    "      {a}\n",
                    a = interpolate(arg, &output_to_var, &sources)
                ));
            }
            nix.push_str("    ];\n");
        }

        // Multi-output declaration.
        let output_names: Vec<&str> = td.drv.outputs.iter().map(|o| o.name.as_str()).collect();
        if output_names.len() > 1
            || output_names.first().map(|n| *n) != Some("out")
        {
            let quoted: Vec<String> = output_names.iter().map(|n| format!("\"{n}\"")).collect();
            nix.push_str(&format!("    outputs = [{}];\n", quoted.join(" ")));
        }

        // Fixed-output derivation attributes.
        for out in &td.drv.outputs {
            if !out.hash.is_empty() {
                let executable = td.drv.env_get("executable") == Some("1");
                if let Ok(h) = hash::guix_to_nix(&out.hash_algo, &out.hash, executable) {
                    nix.push_str(&format!(
                        "    outputHash = {q};\n",
                        q = nix_str_literal(&h.sri)
                    ));
                    nix.push_str("    outputHashAlgo = \"sha256\";\n");
                    let mode = if h.method == "nar" {
                        "recursive"
                    } else {
                        &h.method
                    };
                    nix.push_str(&format!("    outputHashMode = \"{mode}\";\n"));
                }
            }
        }

        // Env vars.  The splicer injects `name`, `system`, `builder` into
        // env (matching what `builtins.derivation` does), so we skip them
        // here since they're already emitted as standard attributes above.
        // Output names and `outputHash*` are also handled separately.
        let skip: &[&str] = &[
            "name",
            "system",
            "builder",
            "outputs",
            "outputHash",
            "outputHashAlgo",
            "outputHashMode",
        ];
        for e in &td.drv.env {
            if skip.contains(&e.key.as_str()) {
                continue;
            }
            if output_names.contains(&e.key.as_str()) {
                continue;
            }
            nix.push_str(&format!(
                "    {k} = {v};\n",
                k = nix_attr_key(&e.key),
                v = interpolate(&e.value, &output_to_var, &sources)
            ));
        }

        nix.push_str("  };\n\n");
    }

    nix.push_str(&format!(
        "in\n  {}\n",
        var_names.last().ok_or("no derivations to emit")?
    ));

    fs::write(out_path, &nix).map_err(|e| format!("write {}: {e}", out_path.display()))?;
    Ok(())
}

// ── helpers ──────────────────────────────────────────────────────────────────

/// Assign a unique Nix variable name to each derivation.
fn assign_var_names(translated: &[TranslatedDrv]) -> Vec<String> {
    let mut names = Vec::with_capacity(translated.len());
    let mut seen: HashMap<String, usize> = HashMap::new();
    for td in translated {
        let base = sanitize_ident(derivation_name(&td.guix_drv_path));
        let count = seen.entry(base.clone()).or_insert(0);
        let name = if *count == 0 {
            base.clone()
        } else {
            format!("{base}_{count}")
        };
        *count += 1;
        names.push(name);
    }
    names
}

/// Turn an arbitrary string into a valid Nix identifier.
fn sanitize_ident(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if s.is_empty() {
        s = "_unnamed".to_string();
    }
    s
}

/// Escape a string for use inside Nix `"..."` (no surrounding quotes).
fn escape_nix(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'\\' => {
                out.push_str("\\\\");
                i += 1;
            }
            b'"' => {
                out.push_str("\\\"");
                i += 1;
            }
            b'$' if i + 1 < bytes.len() && bytes[i + 1] == b'{' => {
                out.push_str("\\${");
                i += 2;
            }
            b'\n' => {
                out.push_str("\\n");
                i += 1;
            }
            b'\r' => {
                out.push_str("\\r");
                i += 1;
            }
            b'\t' => {
                out.push_str("\\t");
                i += 1;
            }
            _ => {
                out.push(bytes[i] as char);
                i += 1;
            }
        }
    }
    out
}

/// A plain Nix string literal with no interpolation.
fn nix_str_literal(s: &str) -> String {
    format!("\"{}\"", escape_nix(s))
}

/// Produce a Nix string with `${var}` interpolation for known store paths.
fn interpolate(
    s: &str,
    output_to_var: &HashMap<&str, (&str, &str)>,
    sources: &HashMap<&str, String>,
) -> String {
    if !s.contains("/nix/store/") {
        return nix_str_literal(s);
    }

    let mut replacements: Vec<(usize, usize, String)> = Vec::new();
    for m in STORE_PATH_RE.find_iter(s) {
        let path = m.as_str();
        if let Some(&(var, out_name)) = output_to_var.get(path) {
            let interp = if out_name == "out" {
                format!("${{{var}}}")
            } else {
                format!("${{{var}.{out_name}}}")
            };
            replacements.push((m.start(), m.end(), interp));
        } else if let Some(var) = sources.get(path) {
            replacements.push((m.start(), m.end(), format!("${{{var}}}")));
        }
    }

    if replacements.is_empty() {
        return nix_str_literal(s);
    }

    let mut out = String::from("\"");
    let mut pos = 0;
    for (start, end, interp) in &replacements {
        out.push_str(&escape_nix(&s[pos..*start]));
        out.push_str(interp);
        pos = *end;
    }
    out.push_str(&escape_nix(&s[pos..]));
    out.push('"');
    out
}

/// Format an attribute key: bare if it's a valid Nix identifier, quoted otherwise.
fn nix_attr_key(key: &str) -> String {
    let valid = !key.is_empty()
        && key
            .chars()
            .next()
            .map(|c| c.is_alphabetic() || c == '_')
            .unwrap_or(false)
        && key.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '-' || c == '\'');
    if valid {
        key.to_string()
    } else {
        format!("\"{}\"", escape_nix(key))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_ident_basic() {
        assert_eq!(sanitize_ident("hello-2.12.2"), "hello_2_12_2");
        assert_eq!(sanitize_ident("0xdeadbeef"), "_0xdeadbeef");
        assert_eq!(sanitize_ident("gcc-core-mesboot0-2.95.3"), "gcc_core_mesboot0_2_95_3");
    }

    #[test]
    fn escape_nix_basic() {
        assert_eq!(escape_nix("hello"), "hello");
        assert_eq!(escape_nix("a\"b"), "a\\\"b");
        assert_eq!(escape_nix("${foo}"), "\\${foo}");
        assert_eq!(escape_nix("$out"), "$out");
        assert_eq!(escape_nix("a\\b"), "a\\\\b");
    }

    #[test]
    fn interpolate_replaces_known_paths() {
        let mut outputs = HashMap::new();
        outputs.insert(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-gcc",
            ("gcc", "out"),
        );
        let sources = HashMap::new();
        assert_eq!(
            interpolate(
                "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-gcc/bin/gcc",
                &outputs,
                &sources
            ),
            "\"${gcc}/bin/gcc\""
        );
    }

    #[test]
    fn interpolate_preserves_unknown_paths() {
        let outputs = HashMap::new();
        let sources = HashMap::new();
        assert_eq!(
            interpolate(
                "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-unknown/bin/x",
                &outputs,
                &sources
            ),
            "\"/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-unknown/bin/x\""
        );
    }

    #[test]
    fn interpolate_handles_shell_dollar_brace() {
        let mut outputs = HashMap::new();
        outputs.insert(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-dep",
            ("dep", "out"),
        );
        let sources = HashMap::new();
        assert_eq!(
            interpolate(
                "echo ${foo} /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-dep/bin/x",
                &outputs,
                &sources
            ),
            "\"echo \\${foo} ${dep}/bin/x\""
        );
    }

    #[test]
    fn interpolate_multi_output() {
        let mut outputs = HashMap::new();
        outputs.insert(
            "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-pkg-lib",
            ("pkg", "lib"),
        );
        let sources = HashMap::new();
        assert_eq!(
            interpolate(
                "-L/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-pkg-lib/lib",
                &outputs,
                &sources
            ),
            "\"-L${pkg.lib}/lib\""
        );
    }

    #[test]
    fn var_names_are_unique() {
        use crate::ast::Derivation;
        let mk = |name: &str| TranslatedDrv {
            guix_drv_path: format!("/gnu/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-{name}.drv"),
            nix_drv_path: String::new(),
            drv: Derivation {
                outputs: vec![],
                input_drvs: vec![],
                input_srcs: vec![],
                system: String::new(),
                builder: String::new(),
                args: vec![],
                env: vec![],
            },
            nix_outputs: HashMap::new(),
        };
        let tds = vec![
            mk("module-import-compiled"),
            mk("module-import-compiled"),
            mk("module-import-compiled"),
        ];
        let names = assign_var_names(&tds);
        assert_eq!(names[0], "module_import_compiled");
        assert_eq!(names[1], "module_import_compiled_1");
        assert_eq!(names[2], "module_import_compiled_2");
    }
}
